### ISSUE TITLE
Statement Keyword Casing 

### ISSUE THREAD

**Issue by hicaro** [bikeshedder/tusker-python-legacy#14]
I'd like to first thank the contributors here. Tusker is awesome! I use it on a daily basis and it has been a great tool on my toolbelt.

I have a minor enhancement request to make. I've noticed that the statement casings are not consistent when generating the diff. Some statements have keywords all upper case, all lower case, or a mixture of both. 

For instance:

```sql
CREATE UNIQUE INDEX some_table_pkey ON some_table USING btree (id);

alter table "some_table" add constraint "some_table_pkey" PRIMARY KEY using index "some_table_pkey";

alter table "some_other_table" alter column "some_column" set not null;
```

It would be great if all keywords in generated statements are consistent. Ideally, but not necessary, it would be great to have a config to either use upper or lower case to fit the developer's preference.

**Comment by bikeshedder** [comment]
The diff is generated using the [migra](https://github.com/djrobstep/migra) library. An issue regarding those inconsistencies is already reported in the migra repository:
- djrobstep/migra#63

**Comment by hicaro** [comment]
@bikeshedder thank you! It seems their issue has been stale for a while. Good to know it is on the radar though.

**Comment by bikeshedder** [comment]
I'm going to close this issue as there is nothing that can be done in tusker to fix that.
