### ISSUE TITLE
TypeError: dict is not a sequence if sql contains %s

### ISSUE THREAD

**Issue by daa** [bikeshedder/tusker-python-legacy#21]
When SQL text contains '%' sign, DB API driver treats it as query parameter placeholder and it leads to ``TypeError: dict is not a sequence`` when executing that SQL without parameters. This behaviour is a consequence of changes made in #18 where SQLAlchemy parameter binding was bypassed but underlying DB-API driver wasn't. My proposed solution is to escape all '%' signs (replace them with double percent: '%%') in SQL text before executing it with driver so that such sequences are not recognized as parameters.

**Comment by bikeshedder** [comment]
Thanks a lot for the patch! :+1: 

I just released Tusker 0.4.8 including your fix: https://pypi.org/project/tusker/0.4.8/

**Comment by daa** [comment]
Thank you very much!
