### ISSUE TITLE
Does the tusker work for multiple schemas in the db?

### ISSUE THREAD

**Issue by geohuz** [bikeshedder/tusker-python-legacy#7]
I've tried using tusker to compare a database which is created by using pg_dump on source db, so after running ```tusker diff database schema``,  it just display all the contents in the schema.sql, and the last line shows:

```
--
-- PostgreSQL database dump complete
--]
(Background on this error at: http://sqlalche.me/e/13/2j85)
```

I don't know what happened at this stage.

**Comment by bikeshedder** [comment]
Could you check if you can actually import that schema file using `psql`?

That looks like an exception which occurred while executing the SQL file. When this happens the output is quite hard to read. The actual error message should be printed right above the file contents which is part of the exception message.

**Comment by geohuz** [comment]
Thanks! I tried to run script against a database temporarily created and found the issues, after fixing those issues the ```tusker database``` run happily!
